%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  MATLAB Code for                                                  %
%                                                                   %
%  Drawing experiment results                                       %
%  Version 1.0 - Aug. 2015                                          %
%                                                                   %
%  According to:                                                    %
%  H.R. Tavakoli, A. Atyabi, Antti Rantanen, Seppo J. Laukka,       %
%  Samia Nefti-Meziani, & Janne Heikkilä,                          %
%  "Predicting the valence of a scene from observers' eye movements"%
%  PLOS ONE, 2015.                                                  %
%                                                                   %
%                                                                   %
%  Programmed By: A. Atyabi                                         %
%                                                                   %
%         e-Mail: a.atyabi@salford.ac.uk                            %
%                 adham.atyabi@flinders.edu.au                      %
%                                                                   %
% Homepage: http://www.seek.salford.ac.uk/profiles/AAtyabi.jsp      %
%                                                                   %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% experiment 1 and supplement experiment 2
close all
clear all
clc
addpath('\Codes-for-PlosOne-paper\function')
addpath('\Codes-for-PlosOne-paper\Results')
Input_File={'saliency_mapRBFSVM10FoldCVF9.mat',...
    'saliency_mapLSVM10FoldCVF9.mat',...
    'saliency_mapPolySVM10FoldCVF9.mat',...
    'top_10_coordinatesRBFSVM10FoldCVF10.mat',...
    'top_10_coordinatesPolySVM10FoldCVF10.mat',...
    'top_10_coordinatesLSVM10FoldCVF10.mat',...
    'fixation_histogramRBFSVM10FoldCVF7.mat',...
    'fixation_histogramPolySVM10FoldCVF7.mat',...
    'fixation_histogramLSVM10FoldCVF7.mat',...
    'saliency_histogramRBFSVM10FoldCVF8.mat',...
    'saliency_histogramPolySVM10FoldCVF8.mat',...
    'saliency_histogramLSVM10FoldCVF8.mat',...
    'fixation_durationRBFSVM10FoldCVF6.mat',...
    'fixation_durationPolySVM10FoldCVF6.mat',...
    'fixation_durationLSVM10FoldCVF6.mat',...
    'saccade_durationRBFSVM10FoldCVF5.mat',...
    'saccade_durationPolySVM10FoldCVF5.mat',...
    'saccade_durationLSVM10FoldCVF5.mat',...
    'saccade_lngthRBFSVM10FoldCVF3.mat',...
    'saccade_lngthPolySVM10FoldCVF3.mat',...
    'saccade_lngthLSVM10FoldCVF3.mat',...
    'slopeRBFSVM10FoldCVF4.mat',...
    'slopePolySVM10FoldCVF4.mat',...
    'slopeLSVM10FoldCVF4.mat',...
    'saccade_orientationRBFSVM10FoldCVF2.mat',...
    'saccade_orientationLSVM10FoldCVF2.mat',...
    'saccade_orientationPolySVM10FoldCVF2.mat',...
    'velocityRBFSVM10FoldCVF1.mat',...
    'velocityPolySVM10FoldCVF1.mat',...
    'velocityLSVM10FoldCVF1.mat',...    
    'RBFTst10FoldCVELM.mat',...
    'PolyTst10FoldCVELM.mat',...
    'LinTst10FoldCVELM.mat'};
f={'fixation density map','top 10 salient locations','fixation histogram','saliency histogram','histogram of fixation duration','histogram of saccade duration','histogram of saccade length','histogram of saccade slope','histogram of saccade orientation','histogram of saccade velocity','Full Set'};
k={'RBFSVM','PolynomialSVM','LinearSVM'};
sub={'T'};cn=1;
for j=1:size(f,2)
    for i=1:size(k,2)
        for l=1:1
            CL{cn}=k{i};
            Subject{cn}=sub{l};
            FE{cn}=f{j};
            Discription{cn}.FE=FE{cn};
            Discription{cn}.CL=CL{cn};
            Discription{cn}.Subject=Subject{cn};
            cn=cn+1;
        end
    end
end
d_LSVM=Open_Result_File(Input_File,Discription,FE,CL,Subject,k,f,sub);
[d_LSVM]=Categorization_Func(d_LSVM);

Input_File={'SumNewTmpRBFBagMix10FoldCVF9.mat',...
    'SumNewTmpPolyBagMix10FoldCVF9.mat',...
    'SumNewTmpLinBagMix10FoldCVF9.mat',...
    'SumNewTmpRBFBagMix10FoldCVF10.mat',...
    'SumNewTmpPolyBagMix10FoldCVF10.mat',...
    'SumNewTmpLinBagMix10FoldCVF10.mat',...
    'SumNewTmpRBFBagMix10FoldCVF7.mat',...
    'SumNewTmpPolyBagMix10FoldCVF7.mat',...
    'SumNewTmpLinBagMix10FoldCVF7.mat',...
    'SumNewTmpRBFBagMix10FoldCVF8.mat',...
    'SumNewTmpPolyBagMix10FoldCVF8.mat',...
    'SumNewTmpLinBagMix10FoldCVF8.mat',...
    'SumNewTmpRBFBagMix10FoldCVF6.mat',...
    'SumNewTmpPolyBagMix10FoldCVF6.mat',...
    'SumNewTmpLinBagMix10FoldCVF6.mat',...
    'SumNewTmpRBFBagMix10FoldCVF5.mat',...
    'SumNewTmpPolyBagMix10FoldCVF5.mat',...
    'SumNewTmpLinBagMix10FoldCVF5.mat',...
    'SumNewTmpRBFBagMix10FoldCVF3.mat',...
    'SumNewTmpPolyBagMix10FoldCVF3.mat',...
    'SumNewTmpLinBagMix10FoldCVF3.mat',...
    'SumNewTmpRBFBagMix10FoldCVF4.mat',...
    'SumNewTmpPolyBagMix10FoldCVF4.mat',...
    'SumNewTmpLinBagMix10FoldCVF4.mat',...
    'SumNewTmpRBFBagMix10FoldCVF2.mat',...
    'SumNewTmpPolyBagMix10FoldCVF2.mat',...
    'SumNewTmpLinBagMix10FoldCVF2.mat',...
    'SumNewTmpRBFBagMix10FoldCVF1.mat',...
    'SumNewTmpPolyBagMix10FoldCVF1.mat',...
    'SumNewTmpLinBagMix10FoldCVF1.mat',...    
    'SumNewTmpRBFBagMix10FoldCVF11.mat',...
    'SumNewTmpPolyBagMix10FoldCVF11.mat',...
    'SumNewTmpLinBagMix10FoldCVF11.mat',...    
    };
f={'fixation density map','top 10 salient locations','fixation histogram','saliency histogram','histogram of fixation duration','histogram of saccade duration','histogram of saccade length','histogram of saccade slope','histogram of saccade orientation','histogram of saccade velocity','Full Set'};
k={'RBFSVM','PolynomialSVM','LinearSVM'};
sub={'T'};cn=1;
for j=1:size(f,2)
    for i=1:size(k,2)
        for l=1:1
            CL{cn}=k{i};
            Subject{cn}=sub{l};
            FE{cn}=f{j};
            Discription{cn}.FE=FE{cn};
            Discription{cn}.CL=CL{cn};
            Discription{cn}.Subject=Subject{cn};
            cn=cn+1;
        end
    end
end
d_SUM=Open_Result_File(Input_File,Discription,FE,CL,Subject,k,f,sub);
[d_SUM]=Categorization_Func(d_SUM);

Input_File={'NewSumNewTmpRBFBagMix10FoldCVF9.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF9.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF9.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF10.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF10.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF10.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF7.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF7.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF7.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF8.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF8.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF8.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF6.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF6.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF6.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF5.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF5.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF5.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF3.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF3.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF3.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF4.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF4.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF4.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF2.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF2.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF2.mat',...
    'NewSumNewTmpRBFBagMix10FoldCVF1.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF1.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF1.mat',...    
    'NewSumNewTmpRBFBagMix10FoldCVF11.mat',...
    'NewSumNewTmpPolyBagMix10FoldCVF11.mat',...
    'NewSumNewTmpLinBagMix10FoldCVF11.mat',...    
    };
f={'fixation density map','top 10 salient locations','fixation histogram','saliency histogram','histogram of fixation duration','histogram of saccade duration','histogram of saccade length','histogram of saccade slope','histogram of saccade orientation','histogram of saccade velocity','Full Set'};
k={'RBFSVM','PolynomialSVM','LinearSVM'};
sub={'T'};cn=1;
for j=1:size(f,2)
    for i=1:size(k,2)
        for l=1:1
            CL{cn}=k{i};
            Subject{cn}=sub{l};
            FE{cn}=f{j};
            Discription{cn}.FE=FE{cn};
            Discription{cn}.CL=CL{cn};
            Discription{cn}.Subject=Subject{cn};
            cn=cn+1;
        end
    end
end
d2_SUM=Open_Result_File(Input_File,Discription,FE,CL,Subject,k,f,sub);
[d2_SUM]=Categorization_Func(d2_SUM);

Input_File={'NewWeightSumNewTmpRBFBagMix10FoldCVF9.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF9.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF9.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF10.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF10.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF10.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF7.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF7.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF7.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF8.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF8.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF8.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF6.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF6.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF6.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF5.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF5.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF5.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF3.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF3.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF3.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF4.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF4.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF4.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF2.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF2.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF2.mat',...
    'NewWeightSumNewTmpRBFBagMix10FoldCVF1.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF1.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF1.mat',...    
    'NewWeightSumNewTmpRBFBagMix10FoldCVF11.mat',...
    'NewWeightSumNewTmpPolyBagMix10FoldCVF11.mat',...
    'NewWeightSumNewTmpLinBagMix10FoldCVF11.mat',...    
    };
f={'fixation density map','top 10 salient locations','fixation histogram','saliency histogram','histogram of fixation duration','histogram of saccade duration','histogram of saccade length','histogram of saccade slope','histogram of saccade orientation','histogram of saccade velocity','Full Set'};
k={'RBFSVM','PolynomialSVM','LinearSVM'};
sub={'T'};cn=1;
for j=1:size(f,2)
    for i=1:size(k,2)
        for l=1:1
            CL{cn}=k{i};
            Subject{cn}=sub{l};
            FE{cn}=f{j};
            Discription{cn}.FE=FE{cn};
            Discription{cn}.CL=CL{cn};
            Discription{cn}.Subject=Subject{cn};
            cn=cn+1;
        end
    end
end
d2_WeightSUM=Open_Result_File(Input_File,Discription,FE,CL,Subject,k,f,sub);
[d2_WeightSUM]=Categorization_Func(d2_WeightSUM);

cap='The impact of Bagging on individual feature types';
cap2={'Individual Features','Individual Features + Summation Bagging','Individual Features + Weighted Summation Bagging'};
P={''};
X{1}.d=d_LSVM;
X{2}.d=d2_SUM;
X{3}.d=d2_WeightSUM;
Draw_FE_Subject({'fixation density map','top 10 salient locations','fixation histogram','saliency histogram','histogram of fixation duration','histogram of saccade duration','histogram of saccade length','histogram of saccade slope','histogram of saccade orientation','histogram of saccade velocity','Full Set'},{' '},X,cap,cap2,45)
%%
% supplement experiment 1
clear all
close all
clc
addpath('\Codes-for-PlosOne-paper\function')
addpath('\Codes-for-PlosOne-paper\Results')
Input_File={
    'RBFSFSF10FoldCVDef.mat',...
    'PolySFSF10FoldCVDef.mat',...
    'LinSFSF10FoldCVDef.mat',...
    'RBFSFSB10FoldCVDef.mat',...
    'PolySFSB10FoldCVDef.mat',...
    'LinSFSB10FoldCVDef.mat',...
    'RBFTstSVD10FoldCVSVM.mat',...
    'PolyTstSVD10FoldCVSVM.mat',...
    'LinTstSVD10FoldCVSVM.mat',...     
    'RBFTstPCA10FoldCVSVM.mat',...
    'PolyTstPCA10FoldCVSVM.mat',...
    'LinTstPCA10FoldCVSVM.mat',...    
    'RBFTstGADecomposition10FoldCVELM.mat',...
    'PolyTstGADecomposition10FoldCVELM.mat',...
    'LinTstGADecomposition10FoldCVELM.mat',...
    'RBFTstHalfPSODecompM210FoldCV.mat',...
    'PolyTstHalfPSODecompM210FoldCV.mat',...
    'LinTstHalfPSODecompM210FoldCV.mat',...
    'RBFTstPSODecomposition10FoldCV.mat',...
    'PolyTstPSODecomposition10FoldCV.mat',...
    'LinTstPSODecomposition10FoldCV.mat',...
    'RBFTstPSODecompositionM210FoldCV.mat',...
    'PolyTstPSODecompositionM210FoldCV.mat',...
    'LinTstPSODecompositionM210FoldCV.mat',...
    'RBFTstFixPSODecompositionM210FoldCV.mat',...
    'PolyTstFixPSODecompositionM210FoldCV.mat',...
    'LinTstFixPSODecompositionM210FoldCV.mat',...
    'RBFTst10FoldCVELM.mat',...
    'PolyTst10FoldCVELM.mat',...
    'LinTst10FoldCVELM.mat'};
f={'SFS','SBS','SVD','PCA','GA-based decomposition','Mutated PSO-based decomposition 2','PSO-based decomposition 1','Mutated PSO-based decomposition 1','Mutated PSO-based decomposition 3','Full Set'};
k={'RBFSVM','PolynomialSVM','LinearSVM'};
sub={'T'};cn=1;
for j=1:size(f,2)
    for i=1:size(k,2)
        for l=1:1
            CL{cn}=k{i};
            Subject{cn}=sub{l};
            FE{cn}=f{j};
            Discription{cn}.FE=FE{cn};
            Discription{cn}.CL=CL{cn};
            Discription{cn}.Subject=Subject{cn};
            cn=cn+1;
        end
    end
end
d_LSVM=Open_Result_File(Input_File,Discription,FE,CL,Subject,k,f,sub);
[d_LSVM]=Categorization_Func(d_LSVM);

cap='The impact of reapplying PSO masks using CARD1000Hz0.5s5*280';
cap2={'VV','VV'};
P={''};
X{1}.d=d_LSVM;
X{2}.d=d_LSVM;
Draw_FE_Subject({'SFS','SBS','SVD','PCA','GA-based decomposition','Mutated PSO-based decomposition 2','PSO-based decomposition 1','Mutated PSO-based decomposition 1','Mutated PSO-based decomposition 3','Full Set'},{'t'},X,cap,cap2,60)
%%
%  experiment 2

clear all
close all
clc
addpath('\Codes-for-PlosOne-paper\function')
addpath('\Codes-for-PlosOne-paper\Results')
Input_File={
    'RBFSFSF10FoldCVDef.mat',...
    'PolySFSF10FoldCVDef.mat',...
    'LinSFSF10FoldCVDef.mat',...
    'RBFSFSB10FoldCVDef.mat',...
    'PolySFSB10FoldCVDef.mat',...
    'LinSFSB10FoldCVDef.mat',...
    'RBFTstSVD10FoldCVSVM.mat',...
    'PolyTstSVD10FoldCVSVM.mat',...
    'LinTstSVD10FoldCVSVM.mat',...     
    'RBFTstPCA10FoldCVSVM.mat',...
    'PolyTstPCA10FoldCVSVM.mat',...
    'LinTstPCA10FoldCVSVM.mat',...    
    'RBFTstGADecomposition10FoldCVELM.mat',...
    'PolyTstGADecomposition10FoldCVELM.mat',...
    'LinTstGADecomposition10FoldCVELM.mat',...
    'RBFTstHalfPSODecompM210FoldCV.mat',...
    'PolyTstHalfPSODecompM210FoldCV.mat',...
    'LinTstHalfPSODecompM210FoldCV.mat',...
    'RBFTstGAEarlyFusion10FoldCVELM.mat',...
    'PolyTstGAEarlyFusion10FoldCVELM.mat',...
    'LinTstGAEarlyFusion10FoldCVELM.mat',...
    'RBFTst10FoldCVELM.mat',...
    'PolyTst10FoldCVELM.mat',...
    'LinTst10FoldCVELM.mat'};
f={'SFS','SBS','SVD','PCA','GA-based decomposition','Mutated PSO-based decomposition 2','GA-based feature selection','Full Set'};
k={'RBFSVM','PolynomialSVM','LinearSVM'};
sub={'T'};cn=1;
for j=1:size(f,2)
    for i=1:size(k,2)
        for l=1:1
            CL{cn}=k{i};
            Subject{cn}=sub{l};
            FE{cn}=f{j};
            Discription{cn}.FE=FE{cn};
            Discription{cn}.CL=CL{cn};
            Discription{cn}.Subject=Subject{cn};
            cn=cn+1;
        end
    end
end
d_LSVM=Open_Result_File(Input_File,Discription,FE,CL,Subject,k,f,sub);
[d_LSVM]=Categorization_Func(d_LSVM);

cap='The impact of reapplying PSO masks using CARD1000Hz0.5s5*280';
cap2={'VV','VV'};
P={''};
X{1}.d=d_LSVM;
X{2}.d=d_LSVM;
Draw_FE_Subject({'SFS','SBS','SVD','PCA','GA-based decomposition','Mutated PSO-based decomposition 2','GA-based feature selection','Full Set'},{' '},X,cap,cap2,60)
%%